[workspace.package]
version = "0.0.1"
description = "Tauri Redis."
authors = ["wangziling <sling1994@live.com>"]
license = "MIT"
repository = "https://github.com/wangziling/tauri-redis"
edition = "2021"
readme = "README.md"

[workspace]
members = ["app", "core", "config"]
resolver = "2"

[workspace.dependencies]
tauri_redis = { path = "./app" }
tauri_redis_core = { path = "./core" }
tauri_redis_config = { path = "./config" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "1.0"
