[package]
name = "tauri-redis-config"
version.workspace = true
description.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
readme.workspace = true

[lib]
path = "lib.rs"
