[redis]
connection_timeout = 8

[connections]
filename = "connections.json"
file_cache_manager_key = "connections"

[miscs]
filename = "miscs.json"
file_cache_manager_key = "miscs"

[settings]
filename = "settings.json"
